- hosts: web
  become: yes
  gather_facts: true
  tasks:

  - name: copy filebeat.deb
    copy:
      src: /downloads/filebeat-7.5.0-amd64.deb
      dest: /home/admin

  - name: install filebeat
    apt:
      deb: "/home/admin/filebeat-7.5.0-amd64.deb"

  - name: copy filebeat config file
    template:
      src: /etc/diplom/Diplom_SYS/ansible/filebeat.j2
      dest: /etc/filebeat/filebeat.yml

  - name: Make sure a service is running
    systemd:
      state: started
      name: filebeat
